/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CalendarEntry } from "./utils/calendar-entry";
export namespace Components {
    interface Idk2 {
        "currentYear": number;
        "limits": any;
        "lowerLimitYear": any;
        "selectedMonth": any;
        "upperLimitYear": any;
    }
    interface Idk22 {
        "currentMonth": string;
        "currentYear": number;
        "limits": any;
        "upperLimitYear": number;
        "year": any[];
    }
    interface MyComponent {
        /**
          * @props
         */
        "dayNames": any[];
        "hasMinMax": boolean;
        "limitLower": number;
        "limitUpper": number;
        "monthNames": any[];
        "showFillDays": boolean;
    }
}
export interface Idk2CustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIdk2Element;
}
export interface Idk22CustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLIdk22Element;
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLIdk2Element extends Components.Idk2, HTMLStencilElement {
    }
    var HTMLIdk2Element: {
        prototype: HTMLIdk2Element;
        new (): HTMLIdk2Element;
    };
    interface HTMLIdk22Element extends Components.Idk22, HTMLStencilElement {
    }
    var HTMLIdk22Element: {
        prototype: HTMLIdk22Element;
        new (): HTMLIdk22Element;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "idk-2": HTMLIdk2Element;
        "idk-22": HTMLIdk22Element;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Idk2 {
        "currentYear"?: number;
        "limits"?: any;
        "lowerLimitYear"?: any;
        "onSelectedMonthEvent"?: (event: Idk2CustomEvent<any>) => void;
        "selectedMonth"?: any;
        "upperLimitYear"?: any;
    }
    interface Idk22 {
        "currentMonth"?: string;
        "currentYear"?: number;
        "limits"?: any;
        "onSelectedDate"?: (event: Idk22CustomEvent<{ monthIndex: Number; month: string | number; year: string }>) => void;
        "upperLimitYear"?: number;
        "year"?: any[];
    }
    interface MyComponent {
        /**
          * @props
         */
        "dayNames"?: any[];
        "hasMinMax"?: boolean;
        "limitLower"?: number;
        "limitUpper"?: number;
        "monthNames"?: any[];
        "onDayChanged"?: (event: MyComponentCustomEvent<CalendarEntry>) => void;
        "onMonthChanged"?: (event: MyComponentCustomEvent<CalendarEntry>) => void;
        "showFillDays"?: boolean;
    }
    interface IntrinsicElements {
        "idk-2": Idk2;
        "idk-22": Idk22;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "idk-2": LocalJSX.Idk2 & JSXBase.HTMLAttributes<HTMLIdk2Element>;
            "idk-22": LocalJSX.Idk22 & JSXBase.HTMLAttributes<HTMLIdk22Element>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
